add_newline = true

command_timeout = 2000

#[line_break]
#disabled=true


[character]
error_symbol = "[ âœ— ](bold bright-red) "
vicmd_symbol = "[ â® ](bold bright-cyan)"
success_symbol="[ â¯ ](bold bright-green)"

[time]
disabled = true
time_format = "%v %r"
format = "[$time]($style) "
style = "bold purple"
use_12hr= true
utc_time_offset= "local"

[directory]
truncation_length = 100
truncate_to_repo = false
style = "bold bright-blue"
format = "in [$path]($style)[$read_only]($read_only_style) "

[username]
style_user = "bright-yellow bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format =  "at [$hostname](bold bright-red) "
trim_at = ".companyname.com"
disabled = false

[conda]
symbol="ğŸ…’  "
format = "[$symbol$environment](bright-green) "

[shell]
fish_indicator = "ğŸ³"
bash_indicator = "ğŸ¥Š"
unknown_indicator = "mystery shell"
disabled = false

[jobs]
symbol= "ğŸ› ï¸  "

[battery]
disabled=false
full_symbol = "ï•¸ " 
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "
empty_symbol = "ï– "


[memory_usage]
symbol="ï¡š "
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 70
style = "bold dimmed white"
disabled = true
