
command_timeout = 2000

#[line_break]
#disabled=true

[character]
error_symbol = "[ ✗ ](bold bright-red) "
vicmd_symbol = "[ ❮ ](bold bright-cyan)"
success_symbol="[ ❯ ](bold bright-green)"

[directory]
truncation_length = 100
truncate_to_repo = false
style = "bold bright-blue"
format = "in [$path]($style)[$read_only]($read_only_style) "

[username]
style_user = "bright-yellow bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format =  "at [$hostname](bold bright-red) "
trim_at = ".companyname.com"
disabled = false
